### ISSUE TITLE
Tunning feature

### ISSUE THREAD

**Issue by thiago-porto25** [thiago-porto25/tuner#7]
# Todo:

## Accesscibility
- [ ] Do a rundown after the feature is almost finshed to find points where accessibility can be enhanced

## Meter Component
- [x] Create jsx structure for center and bottom
- [x] Create jsx structure for top
- [x] Style center and bottom
- [x] Use text with different font for sharps and flats for the Big Note
- [x] Style top
- [ ] Create jest tests
- [x] Create logic for moving the ball
- [ ] Create animations for moving the ball
- [x] Create logic for changing the colors
- [ ] Create animation for changing colors
- [ ] Create tests for getColorByCents
- [ ] Add correct colors for getColorByCents
- [x] Create logic for changing colors of the note

## Recording logic
- [x] Request permissions
- [x] If permissions are already granted start recording 
- [x] If user denies permission update create a modal that blocks the screen until permissions are granted
- [x] If an error occurs with permissions create a modal that prompts the user to be requested for permissions again
- [x] If permissions are granted start recording and save it locally to pass to tuner
- [x] When leaving the app delete all recordings (maybe record them as temp files)
- [x] reformulate permission logic into its own component

## pitchfinder logic
- [x] Create logic for parsing the audio recorded in real time
- [x] use the installed packages to translate audio into notes (pitch values)
- [x] Use the translated pitch values to know how far off tune they are. 

## Tuner Screen

- [ ] Create jsx strucutre
- [ ] Style
- [ ] Create jest tests
- [ ] Create i18n texts for en
- [ ] Create i18n texts for pt

## TunerPermissionsHandler
- [x] Create jsx structure
- [x] Create jest tests
- [x] Reformulate logic to send user to app's config screen when the permission is never ask again
- [x] Refactor arePermissionsGranted to be part of redux state

## useNoteDetector
- [x] Unify nomenclature as note detector
- [x] Create hook logic
- [x] Create jest tests

## ActionModal component shared
- [x] Create jsx strucutre
- [x] Style
- [x] Create jest tests
- [x] Create variants for the buttons
- [ ] Fix act issue on tests

## Permission Error Modal component
- [x] Create i18n texts for en
- [x] Create i18n texts for pt
- [x] Create jest tests
- [x] Create handleOnPress to try again

## Permission Denied Modal component
- [x] Create i18n texts for en
- [x] Create i18n texts for pt
- [x] Create jest tests
- [x] Create handleOnPress to try again
- [x] Create handleOnPress to leave app

## Misc
- [x] Find the reason for the performance issues
- [x] Create gherkin to be executed in e2e tests
- [ ] Create e2e tests for the feature
- [x] Test performance and rerenders for the noteDetector hook and the permission handler
